controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_two_dof_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
  - name: fake_three_dof_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
  - name: fake_four_dof_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
  - name: fake_five_dof_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
  - name: fake_right_eef_controller
    joints:
      - right_robotiq_85_left_knuckle_joint